name: Optimize PNG Images

on:
  push:
    # Only run when PNG images change
    paths:
      - 'games/**/*.png'
      - 'games/**/*.PNG'

permissions:
  contents: write

jobs:
  optimize:
    # Prevent recursion when the workflow's own commit pushes back
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pngquant
        run: |
          sudo apt-get update
          sudo apt-get install -y pngquant

      - name: Optimize PNG images
        shell: bash
        run: |
          set -euo pipefail
          # Optimize all PNGs in games/images (safe to run repeatedly)
          if [ -d games/images ]; then
            find games/images -type f \( -iname '*.png' -o -iname '*.PNG' \) -print0 | \
              xargs -0 -n1 -P 4 bash -lc 'pngquant --force --skip-if-larger --strip --speed 1 --quality=70-95 --ext .png "$0"'
          fi
          # Show summary of any changes
          if ! git diff --quiet; then
            echo "Optimization produced changes. Files to update:"
            git status --porcelain
          else
            echo "No image changes after optimization."
          fi

      - name: Commit and push changes
        if: always()
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore(images): optimize PNGs via pngquant [skip-ci]"
            git push
          else
            echo "Nothing to commit."
          fi

